# Generated by Django 5.2.5 on 2025-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_evento_descripcion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lugar",
            options={"verbose_name_plural": "Lugares"},
        ),
        migrations.RemoveField(
            model_name="evento",
            name="modulo",
        ),
        migrations.AlterField(
            model_name="lugar",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="evento",
            name="modulo",
            field=models.ManyToManyField(
                related_name="eventos_modulo", to="eventos.modulo"
            ),
        ),
    ]
