# Generated by Django 5.2.5 on 2025-09-06 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0003_alter_lugar_options_remove_evento_modulo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="creador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
