# Generated by Django 5.2.5 on 2025-08-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleado",
            name="slug",
        ),
    ]
