# Generated by Django 5.2.5 on 2025-09-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_remove_empleado_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empleado",
            options={
                "ordering": ["nombre", "apellidos"],
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
    ]
