# Generated by Django 5.2.5 on 2025-08-19 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="departamento",
            field=models.CharField(default="Psicología", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="respuesta_seguridad_1",
            field=models.CharField(
                max_length=255, verbose_name="¿Cuál es el nombre de tu primera mascota?"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="respuesta_seguridad_2",
            field=models.CharField(
                max_length=255, verbose_name="¿Cuál es el nombre de tu abuela materna?"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telefono",
            field=models.CharField(default="111222333", max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="profiles"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
