# Generated by Django 5.2.5 on 2025-08-21 18:07

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_customuser_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=registration.models.custom_upload_to
            ),
        ),
    ]
