# Generated by Django 5.2.5 on 2025-08-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["user__username"]},
        ),
    ]
