# Generated by Django 5.2.5 on 2025-09-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_alter_profile_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="link",
        ),
    ]
